[package]
name = "rustmill"
version = "0.1.0"
authors = ["belfz <marcinbar1@gmail.com>"]

[dependencies]
image = "0.17.0"
piston_window = "0.73.0"
piston2d-gfx_graphics = "0.46.0"
gfx_device_gl = "0.14.4"
gfx = "0.16.1"

nalgebra = "0.13.1"
ncollide = "0.13.0"
